sonar.organization=ksurahan-source
sonar.projectKey=ksurahan-source_hiob-core
sonar.projectName=hiob-core
sonar.sourceEncoding=UTF-8

sonar.sources=hiob_core,verify_build.sh
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
